language: python

python:
  - "3.12"

install:
  - pip install yamllint mkdocs mkdocs-macros-plugin mkdocs-material mkdocs-material-extensions mkdocs-git-revision-date-plugin mkdocs-git-revision-date-localized-plugin git+https://github.com/ojacques/mkdocs-git-committers-plugin-2@2.3.0

script:
  - mkdocs build --verbose --clean
  # - mkdocs build --verbose --clean --strict

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  on:
    branch: main
