---
site_name: Celestial Codex Wiki
site_description: NAS setups, art, programming, and beyond.
site_url: https://pages.github.com/scottgigawatt/wiki
repo_url: https://github.com/scottgigawatt/wiki
repo_name: scottgigawatt/wiki
edit_uri: edit/main/docs/

theme:
  name: material
  logo_dark_mode: assets/logo-light-mode.svg
  logo_light_mode: assets/logo-light-mode.svg
  favicon: assets/favicon.svg
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - navigation.expand
    - toc.follow
    # - toc.integrate
    - content.action.edit
    - content.code.annotate
    # - header.autohide
  custom_dir: overrides

extra_css:
  - assets/stylesheets/extra.css

# extra_javascript:
#   - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
#   - assets/javascripts/tablesort.js

plugins:
  - search
  - git-revision-date:
      modify_md: false
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: timeago
      fallback_to_build_date: true
      enable_creation_date: true
  - git-committers:
      repository: scottgigawatt/wiki
      branch: main
      enabled: !ENV [CI, true]
      token: !ENV ["MKDOCS_GH_TOKEN"]

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/assets/icons
  - pymdownx.details
  - tables
  - toc:
      permalink: true
      separator: "-"
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink
  - attr_list
  - md_in_html
  - meta
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scottgigawatt/wiki
      name: Wiki

nav:
  - General Topics:
      - About: index.md
      - Using MkDocs:
          - Overview: general/mkdocs.md
          - FAQ: general/mkdocs-faq.md
  - Synology Guides:
      - Direct Ethernet Config: synology-guides/direct-ethernet-config.md
  - Hosting Guides:
      - Hosting and Pool Maintenance: hosting/hosting_and_pool_maintenance.md
